// ============================================================================
// Simple Report Builder Component (JSX version for compatibility)
// ============================================================================

import { useState } from 'react';

const safeWindow = () => ({
  UI: typeof window !== 'undefined' && window.PulseUI || { Button: () => null, Card: () => null, CardHeader: () => null, TOKENS: {}, cx: (...xs) => xs.filter(Boolean).join(" ") }
});

const w = safeWindow();
const Button = w.UI.Button;

function SimpleReportBuilder() {
  const [config, setConfig] = useState({
    name: '',
    fields: [],
    filters: {},
    groupBy: 'department',
    sortBy: 'created_at',
    chartType: 'table',
  });

  const [selectedFields, setSelectedFields] = useState(new Set());

  // Available fields for the report
  const availableFields = [
    { id: 'title', label: 'Issue Title', type: 'text' },
    { id: 'status', label: 'Status', type: 'select', options: [{ label: 'Open', value: 'open' }, { label: 'Closed', value: 'closed' }] },
    { id: 'priority', label: 'Priority', type: 'select', options: [{ label: 'Urgent', value: 'urgent' }, { label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }] },
    { id: 'created_at', label: 'Created Date', type: 'date' },
    { id: 'name', label: 'Guest Name', type: 'text' },
    { id: 'room_number', label: 'Room Number', type: 'text' },
    { id: 'departments', label: 'Department', type: 'select' },
    { id: 'assignedTo', label: 'Assigned To', type: 'select' },
  ];

  const toggleField = (fieldId) => {
    const newSelected = new Set(selectedFields);
    if (newSelected.has(fieldId)) {
      newSelected.delete(fieldId);
    } else {
      newSelected.add(fieldId);
    }
    setSelectedFields(newSelected);

    // Update config
    setConfig(prev => ({
      ...prev,
      fields: availableFields.filter(f => newSelected.has(f.id)),
    }));
  };

  const exportReport = async (format) => {
    try {
      const response = await window.PulseAPI.Issues.list({
        per_page: 1000,
        ...config.filters,
      });

      const data = response.data;

      if (format === 'csv') {
        exportToCSV(data, config.fields);
      } else if (format === 'pdf') {
        exportToPDF(data, config);
      }

      console.log(`Exported as ${format}`);
    } catch (error) {
      console.error('Export failed:', error);
    }
  };

  const exportToCSV = (data, fields) => {
    if (fields.length === 0) {
      alert('Please select at least one field');
      return;
    }

    const headers = fields.map(f => f.label);
    const rows = data.map(item =>
      fields.map(field => {
        const value = getNestedValue(item, field.id);
        return value ?? '';
      })
    );

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.join(',')),
    ].join('\n');

    downloadFile(csvContent, 'report.csv', 'text/csv');
  };

  const exportToPDF = (data, config) => {
    const hotelBranding = {
      hotel_name: 'GuestPulse - Anvaya Bali',
      address: 'Jl. Pantai Mengening, Desa Adat Sading, Mengwi Badung, Bali',
      phone: '+62 361 202 2000',
    };

    const reportDate = new Date().toLocaleDateString();

    let html = `
      <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px;">
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #1d1d1f; margin: 0;">${hotelBranding.hotel_name}</h1>
          <p style="color: #6e6e73; margin: 5px 0;">${hotelBranding.address}</p>
          <p style="color: #6e6e73; margin: 5px 0;">${hotelBranding.phone}</p>
        </div>

        <div style="border-bottom: 2px solid #007aff; padding-bottom: 10px; margin-bottom: 20px;">
          <h2 style="color: #1d1d1f; margin: 0;">${config.name || 'Custom Report'}</h2>
          <p style="color: #6e6e73; margin: 5px 0;">Generated: ${reportDate}</p>
        </div>

        <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
          <thead>
            <tr style="background-color: #f5f5f7;">
              ${config.fields.map(field => `<th style="padding: 10px; text-align: left; border-bottom: 1px solid #d1d1d6;">${field.label}</th>`).join('')}
            </tr>
          </thead>
          <tbody>
            ${data.slice(0, 50).map(item => `
              <tr>
                ${config.fields.map(field => `<td style="padding: 10px; border-bottom: 1px solid #e5e5e5;">${getNestedValue(item, field.id) ?? '-'}</td>`).join('')}
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div style="text-align: center; color: #6e6e73; font-size: 12px; margin-top: 40px;">
          <p>Generated by GuestPulse Hotel Operations System</p>
          <p>Page 1 of 1</p>
        </div>
      </div>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>${config.name || 'Custom Report'}</title>
        </head>
        <body>${html}</body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const getNestedValue = (obj, path) => {
    return path.split('.').reduce((current, prop) => current?.[prop], obj);
  };

  const downloadFile = (content, filename, type) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  };

  const fieldGroups = [
    { id: 'issue', label: 'Issue Fields', fields: ['title', 'status', 'priority', 'created_at'] },
    { id: 'guest', label: 'Guest Information', fields: ['name', 'room_number'] },
    { id: 'meta', label: 'Metadata', fields: ['departments', 'assignedTo'] },
  ];

  return (
    <div className="max-w-6xl mx-auto p-6">
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-2xl font-semibold tracking-tight mb-2">Custom Report Builder</h1>
        <p className="text-muted-light text-sm">Create custom reports with drag-and-drop fields, filters, and export options.</p>
      </div>

      <div className="grid grid-cols-[1fr_320px] gap-6">
        {/* Main Builder Area */}
        <div className="space-y-4">
          {/* Report Name */}
          <div className="bg-white rounded-xl border border-black/[.06] overflow-hidden">
            <div className="p-4">
              <label className="block text-xs font-semibold text-muted-light uppercase tracking-wider mb-2">
                Report Name
              </label>
              <input
                type="text"
                value={config.name}
                onChange={(e) => setConfig(prev => ({ ...prev, name: e.target.value }))}
                placeholder="Enter report name..."
                className="w-full px-3 py-2 border border-black/10 rounded-lg text-sm"
              />
            </div>
          </div>

          {/* Available Fields */}
          <div className="bg-white rounded-xl border border-black/[.06] overflow-hidden">
            <div className="p-4 border-b border-black/[.05]">
              <h3 className="text-sm font-semibold">Available Fields</h3>
              <p className="text-xs text-muted-light mt-1">Click to add fields to your report</p>
            </div>
            <div className="p-4 space-y-2">
              {fieldGroups.map(group => (
                <div key={group.id}>
                  <h4 className="text-xs font-semibold text-muted-light uppercase tracking-wider mb-2">{group.label}</h4>
                  <div className="grid grid-cols-2 gap-2">
                    {availableFields
                      .filter(f => group.fields.includes(f.id))
                      .map(field => (
                        <button
                          key={field.id}
                          onClick={() => toggleField(field.id)}
                          disabled={selectedFields.has(field.id)}
                          className={`flex items-center gap-2 px-3 py-2 rounded-lg text-left text-sm transition-all duration-100 ${
                            selectedFields.has(field.id)
                              ? 'bg-accent/10 text-accent cursor-not-allowed opacity-50'
                              : 'bg-black/[.04] hover:bg-black/[.08] text-text cursor-pointer'
                          }`}
                        >
                          <span className="text-xs font-medium">{field.label}</span>
                          <span className="text-xs text-muted-light">({field.type})</span>
                        </button>
                      ))}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Selected Fields */}
          {selectedFields.size > 0 && (
            <div className="bg-white rounded-xl border border-black/[.06] overflow-hidden">
              <div className="p-4 border-b border-black/[.05]">
                <h3 className="text-sm font-semibold">Selected Fields ({selectedFields.size})</h3>
                <p className="text-xs text-muted-light mt-1">These fields will appear in your report</p>
              </div>
              <div className="p-4 space-y-2">
                {config.fields.map((field) => (
                  <div
                    key={field.id}
                    className="flex items-center gap-2 px-3 py-2 bg-black/[.04] rounded-lg group"
                  >
                    <div className="flex-1">
                      <span className="text-sm font-medium">{field.label}</span>
                      <span className="text-xs text-muted-light ml-2">({field.type})</span>
                    </div>
                    <button
                      onClick={() => toggleField(field.id)}
                      className="p-1 rounded hover:bg-black/[.08] opacity-0 group-hover:opacity-100"
                    >
                      <span className="text-xs text-muted-light">×</span>
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Sidebar */}
        <div className="space-y-4">
          {/* Export Options */}
          <div className="bg-white rounded-xl border border-black/[.06] overflow-hidden">
            <div className="p-4 border-b border-black/[.05]">
              <h3 className="text-sm font-semibold">Export Options</h3>
            </div>
            <div className="p-4 space-y-3">
              <Button
                variant="outline"
                icon="download"
                onClick={() => exportReport('csv')}
                disabled={config.fields.length === 0}
                className="w-full justify-start"
              >
                Export as CSV
              </Button>
              <Button
                variant="outline"
                icon="download"
                onClick={() => exportReport('pdf')}
                disabled={config.fields.length === 0}
                className="w-full justify-start"
              >
                Export as PDF
              </Button>
            </div>
          </div>

          {/* Group By */}
          <div className="bg-white rounded-xl border border-black/[.06] overflow-hidden">
            <div className="p-4 border-b border-black/[.05]">
              <h3 className="text-sm font-semibold">Group By</h3>
            </div>
            <div className="p-4">
              <select
                value={config.groupBy}
                onChange={(e) => setConfig(prev => ({ ...prev, groupBy: e.target.value }))}
                className="w-full px-3 py-2 border border-black/10 rounded-lg text-sm"
              >
                <option value="department">Department</option>
                <option value="priority">Priority</option>
                <option value="status">Status</option>
                <option value="assignedTo">Assigned To</option>
              </select>
            </div>
          </div>

          {/* Chart Options */}
          <div className="bg-white rounded-xl border border-black/[.06] overflow-hidden">
            <div className="p-4 border-b border-black/[.05]">
              <h3 className="text-sm font-semibold">Chart Type</h3>
            </div>
            <div className="p-4 space-y-2">
              {[
                { value: 'table', label: 'Table View', icon: 'list' },
                { value: 'bar', label: 'Bar Chart', icon: 'chart-bar' },
                { value: 'line', label: 'Line Chart', icon: 'chart-line' },
                { value: 'pie', label: 'Pie Chart', icon: 'chart-pie' },
              ].map(option => (
                <button
                  key={option.value}
                  onClick={() => setConfig(prev => ({ ...prev, chartType: option.value }))}
                  className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-left text-sm transition-all duration-100 ${
                    config.chartType === option.value
                      ? 'bg-accent/10 text-accent'
                      : 'bg-black/[.04] hover:bg-black/[.08] text-text'
                  }`}
                >
                  {option.label}
                </button>
              ))}
            </div>
          </div>

          {/* Quick Info */}
          <div className="bg-blue-50 border border-blue-100 rounded-xl p-4">
            <h4 className="text-xs font-semibold text-blue-900 mb-2">Quick Guide</h4>
            <div className="text-xs text-blue-800 space-y-1">
              <p>1. Select fields from the left panel</p>
              <p>2. Choose export format</p>
              <p>3. Click export to generate report</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

window.SimpleReportBuilder = SimpleReportBuilder;